import { describe, expect, it } from 'vitest';
import { type TranslationSessionSegment } from '../../stores/translationSessionStore.ts';
import { analyzeXliffImport, applyXliffImport, parseXliffImport, type ParsedTransUnit } from '../xliffImport.ts';
import { buildXliffDocument } from '../xliffExport.ts';

const segment = (overrides: Partial<TranslationSessionSegment> = {}): TranslationSessionSegment => ({
  segmentId: 'segment-1', paragraphId: 'paragraph-1', segmentIndex: 0,
  sourceText: 'Source text', sourceHash: 'hash', startOffset: 0, endOffset: 11,
  targetDraft: 'Current target', origin: 'empty', isUserEdited: false,
  status: 'draft', detectedAt: 1, updatedAt: 1, ...overrides,
});
const unit = (overrides: Partial<ParsedTransUnit> = {}): ParsedTransUnit => ({
  id: 'segment-1', sourceText: 'Source text', targetText: 'Incoming target', state: 'translated', ...overrides,
});
const xml = (body: string, attrs = 'version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2"') => (
  `<?xml version="1.0"?><xliff ${attrs}><file><body>${body}</body></file></xliff>`
);

describe('parseXliffImport', () => {
  it('parses XLIFF generated by buildXliffDocument', () => {
    const built = buildXliffDocument([segment({ targetDraft: '번역', status: 'draft' })], { sourceLang: 'en', targetLang: 'ko' });
    expect(built.ok).toBe(true);
    if (!built.ok) return;
    expect(parseXliffImport(built.xml)).toEqual({ ok: true, toolId: 'SmartLinter', units: [
      { id: 'segment-1', sourceText: 'Source text', targetText: '번역', state: 'needs-review-translation' },
    ] });
  });

  it('distinguishes empty targets from missing targets and extracts optional tool ID', () => {
    const result = parseXliffImport(xml([
      '<header><tool tool-id="CAT"/></header>',
      '<trans-unit id="a"><source>A</source><target/></trans-unit>',
      '<trans-unit id="b"><source>B</source><target></target></trans-unit>',
      '<trans-unit id="c"><source>C</source></trans-unit>',
    ].join('')));
    expect(result).toEqual({ ok: true, toolId: 'CAT', units: [
      { id: 'a', sourceText: 'A', targetText: '', state: null },
      { id: 'b', sourceText: 'B', targetText: '', state: null },
      { id: 'c', sourceText: 'C', targetText: null, state: null },
    ] });
    const withoutTool = parseXliffImport(xml('<trans-unit id="a"><source>A</source></trans-unit>'));
    expect(withoutTool.ok && withoutTool.toolId).toBeNull();
  });

  it.each([
    ['malformed XML', '<xliff>', 'XML_PARSE_ERROR'],
    ['non-xliff root', '<root/>', 'UNSUPPORTED_STRUCTURE'],
    ['wrong version', xml('<trans-unit id="a"><source>A</source></trans-unit>', 'version="2.0" xmlns="urn:oasis:names:tc:xliff:document:1.2"'), 'UNSUPPORTED_STRUCTURE'],
    ['zero trans-units', xml(''), 'UNSUPPORTED_STRUCTURE'],
  ])('rejects %s', (_label, content, reason) => {
    const result = parseXliffImport(content);
    expect(result).toMatchObject({ ok: false, reason });
  });
});

describe('analyzeXliffImport', () => {
  it('covers duplicate, not-found, source mismatch, absent target, unchanged, auto empty, and empty conflict branches', () => {
    const segments = [
      segment({ segmentId: 'unchanged', targetDraft: 'Same', isUserEdited: true }),
      segment({ segmentId: 'auto-empty', targetDraft: 'Old', isUserEdited: false }),
      segment({ segmentId: 'conflict-empty', targetDraft: 'Old', isUserEdited: true }),
      segment({ segmentId: 'mismatch', sourceText: 'Current source' }),
      segment({ segmentId: 'not-provided' }),
      segment({ segmentId: 'dup' }),
    ];
    const analysis = analyzeXliffImport([
      unit({ id: 'dup' }), unit({ id: 'dup', targetText: 'Other' }),
      unit({ id: 'missing' }), unit({ id: 'mismatch', sourceText: 'Old source' }),
      unit({ id: 'not-provided', targetText: null }), unit({ id: 'unchanged', targetText: 'Same' }),
      unit({ id: 'auto-empty', targetText: '' }), unit({ id: 'conflict-empty', targetText: '' }),
    ], segments);
    expect(analysis.skippedDuplicateId).toEqual(['dup']);
    expect(analysis.skippedNotFound.map((item) => item.id)).toEqual(['missing']);
    expect(analysis.skippedSourceMismatch.map((item) => item.id)).toEqual(['mismatch']);
    expect(analysis.notProvided.map((item) => item.id)).toEqual(['not-provided']);
    expect(analysis.autoApply.map((item) => item.segment.segmentId)).toEqual(['unchanged', 'auto-empty']);
    expect(analysis.conflicts.map((item) => item.segment.segmentId)).toEqual(['conflict-empty']);
  });
});

describe('applyXliffImport', () => {
  it('applies automatic and selected incoming values while retaining skipped and kept segments by reference', () => {
    const automatic = segment({ segmentId: 'automatic', targetDraft: 'Old' });
    const useIncoming = segment({ segmentId: 'use', targetDraft: 'Current', isUserEdited: true });
    const keepCurrent = segment({ segmentId: 'keep', targetDraft: 'Keep', isUserEdited: true });
    const unrelated = segment({ segmentId: 'unrelated', targetDraft: 'Untouched' });
    const result = applyXliffImport(
      [automatic, useIncoming, keepCurrent, unrelated],
      [{ segment: automatic, incoming: unit({ id: 'automatic', targetText: '' }) }],
      [
        { segmentId: 'use', resolution: 'use-incoming', incoming: unit({ id: 'use', targetText: 'Imported' }) } as any,
        { segmentId: 'keep', resolution: 'keep-current', incoming: unit({ id: 'keep', targetText: 'Ignored' }) } as any,
      ], 99,
    );
    expect(result[0]).toMatchObject({ targetDraft: '', status: 'untranslated', origin: 'external-cat', isUserEdited: false, updatedAt: 99 });
    expect(result[1]).toMatchObject({ targetDraft: 'Imported', status: 'draft', origin: 'external-cat', isUserEdited: false, updatedAt: 99 });
    expect(result[2]).toBe(keepCurrent);
    expect(result[3]).toBe(unrelated);
  });
});
