import { describe, expect, it } from 'vitest';
import { type TranslationSessionSegment } from '../../stores/translationSessionStore.ts';
import { analyzeXliffImport, applyXliffImport, parseXliffImport, type ParsedTransUnit } from '../xliffImport.ts';
import { buildXliffDocument } from '../xliffExport.ts';

const segment = (overrides: Partial<TranslationSessionSegment> = {}): TranslationSessionSegment => ({
  segmentId: 'segment-1', paragraphId: 'paragraph-1', segmentIndex: 0,
  sourceText: 'Source text', sourceHash: 'hash', startOffset: 0, endOffset: 11,
  targetDraft: 'Current target', origin: 'empty', isUserEdited: false,
  status: 'draft', detectedAt: 1, updatedAt: 1, ...overrides,
});
const unit = (overrides: Partial<ParsedTransUnit> = {}): ParsedTransUnit => ({
  id: 'segment-1', sourceText: 'Source text', targetText: 'Incoming target', state: 'translated', ...overrides,
});
const xml = (body: string, attrs = 'version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2"') => (
  `<?xml version="1.0"?><xliff ${attrs}><file><body>${body}</body></file></xliff>`
);

describe('parseXliffImport', () => {
  it('parses XLIFF generated by buildXliffDocument', () => {
    const built = buildXliffDocument([segment({ targetDraft: '번역', status: 'draft' })], { sourceLang: 'en', targetLang: 'ko' });
    expect(built.ok).toBe(true);
    if (!built.ok) return;
    expect(parseXliffImport(built.xml)).toEqual({ ok: true, toolId: 'SmartLinter', units: [
      { id: 'segment-1', sourceText: 'Source text', targetText: '번역', state: 'needs-review-translation' },
    ] });
  });

  it('distinguishes empty targets from missing targets and extracts optional tool ID', () => {
    const result = parseXliffImport(xml([
      '<header><tool tool-id="CAT"/></header>',
      '<trans-unit id="a"><source>A</source><target/></trans-unit>',
      '<trans-unit id="b"><source>B</source><target></target></trans-unit>',
      '<trans-unit id="c"><source>C</source></trans-unit>',
    ].join('')));
    expect(result).toEqual({ ok: true, toolId: 'CAT', units: [
      { id: 'a', sourceText: 'A', targetText: '', state: null },
      { id: 'b', sourceText: 'B', targetText: '', state: null },
      { id: 'c', sourceText: 'C', targetText: null, state: null },
    ] });
    const withoutTool = parseXliffImport(xml('<trans-unit id="a"><source>A</source></trans-unit>'));
    expect(withoutTool.ok && withoutTool.toolId).toBeNull();
  });

  it.each([
    ['malformed XML', '<xliff>', 'XML_PARSE_ERROR'],
    ['non-xliff root', '<root/>', 'UNSUPPORTED_STRUCTURE'],
    ['wrong version', xml('<trans-unit id="a"><source>A</source></trans-unit>', 'version="2.0" xmlns="urn:oasis:names:tc:xliff:document:1.2"'), 'UNSUPPORTED_STRUCTURE'],
    ['zero trans-units', xml(''), 'UNSUPPORTED_STRUCTURE'],
  ])('rejects %s', (_label, content, reason) => {
    const result = parseXliffImport(content);
    expect(result).toMatchObject({ ok: false, reason });
  });
});

describe('analyzeXliffImport', () => {
  it('covers duplicate, not-found, source mismatch, absent target, unchanged, auto empty, and empty conflict branches', () => {
    const segments = [
      segment({ segmentId: 'unchanged', targetDraft: 'Same', isUserEdited: true }),
      segment({ segmentId: 'auto-empty', targetDraft: 'Old', isUserEdited: false }),
      segment({ segmentId: 'conflict-empty', targetDraft: 'Old', isUserEdited: true }),
      segment({ segmentId: 'mismatch', sourceText: 'Current source' }),
      segment({ segmentId: 'not-provided' }),
      segment({ segmentId: 'dup' }),
    ];
    const analysis = analyzeXliffImport([
      unit({ id: 'dup' }), unit({ id: 'dup', targetText: 'Other' }),
      unit({ id: 'missing' }), unit({ id: 'mismatch', sourceText: 'Old source' }),
      unit({ id: 'not-provided', targetText: null }), unit({ id: 'unchanged', targetText: 'Same' }),
      unit({ id: 'auto-empty', targetText: '' }), unit({ id: 'conflict-empty', targetText: '' }),
    ], segments);
    expect(analysis.skippedDuplicateId).toEqual(['dup']);
    expect(analysis.skippedNotFound.map((item) => item.id)).toEqual(['missing']);
    expect(analysis.skippedSourceMismatch.map((item) => item.id)).toEqual(['mismatch']);
    expect(analysis.notProvided.map((item) => item.id)).toEqual(['not-provided']);
    expect(analysis.autoApply.map((item) => item.segment.segmentId)).toEqual(['unchanged', 'auto-empty']);
    expect(analysis.conflicts.map((item) => item.segment.segmentId)).toEqual(['conflict-empty']);
  });

  it('parses matching inline codes, accepts moved target code positions, and applies taggedTarget', () => {
    const tagged = segment({ sourceText: 'A bold word', taggedSource: { tagStatus: 'valid', sourceTokens: [
      { type: 'text', value: 'A ' }, { type: 'open', id: 'b1', kind: 'bold' },
      { type: 'text', value: 'bold' }, { type: 'close', id: 'b1', kind: 'bold' }, { type: 'text', value: ' word' },
    ] } });
    const parsed = parseXliffImport(xml('<trans-unit id="segment-1"><source>A <bpt id="b1" ctype="x-bold">&lt;b&gt;</bpt>bold<ept id="b1">&lt;/b&gt;</ept> word</source><target><bpt id="b1" ctype="x-bold">&lt;b&gt;</bpt>번역<ept id="b1">&lt;/b&gt;</ept>문장</target></trans-unit>'));
    expect(parsed.ok).toBe(true);
    if (!parsed.ok) return;
    expect(parsed.units[0]).toMatchObject({ sourceText: 'A bold word', targetText: '번역문장' });
    expect(parsed.units[0].sourceTokens).toEqual(tagged.taggedSource!.sourceTokens);
    const analysis = analyzeXliffImport(parsed.units, [tagged]);
    expect(analysis.autoApply).toHaveLength(1);
    const applied = applyXliffImport([tagged], analysis.autoApply, [], 2);
    expect(applied[0].taggedTarget?.targetTokens).toEqual(parsed.units[0].targetTokens);
  });

  it('accepts target inline spans reordered by translation word order', () => {
    const tagged = segment({ sourceText: 'Click the Save button and view Manual.', taggedSource: { tagStatus: 'valid', sourceTokens: [
      { type: 'text', value: 'Click the ' }, { type: 'open', id: 'bold-1', kind: 'bold' },
      { type: 'text', value: 'Save' }, { type: 'close', id: 'bold-1', kind: 'bold' },
      { type: 'text', value: ' button and view ' }, { type: 'open', id: 'italic-1', kind: 'italic' },
      { type: 'text', value: 'Manual' }, { type: 'close', id: 'italic-1', kind: 'italic' }, { type: 'text', value: '.' },
    ] } });
    const analysis = analyzeXliffImport([unit({
      sourceText: tagged.sourceText, sourceTokens: tagged.taggedSource!.sourceTokens,
      targetText: '설명서를 보고 저장 버튼을 누르세요.', targetTokens: [
        { type: 'open', id: 'italic-1', kind: 'italic' }, { type: 'text', value: '설명서' },
        { type: 'close', id: 'italic-1', kind: 'italic' }, { type: 'text', value: '를 보고 ' },
        { type: 'open', id: 'bold-1', kind: 'bold' }, { type: 'text', value: '저장' },
        { type: 'close', id: 'bold-1', kind: 'bold' }, { type: 'text', value: ' 버튼을 누르세요.' },
      ],
    })], [tagged]);
    expect(analysis.skippedInlineCodeIssue).toHaveLength(0);
    expect(analysis.autoApply).toHaveLength(1);
  });

  it.each([
    ['changes a span kind', [
      { type: 'open', id: 'italic-1', kind: 'bold' }, { type: 'text', value: '설명서' },
      { type: 'close', id: 'italic-1', kind: 'bold' }, { type: 'open', id: 'bold-1', kind: 'bold' },
      { type: 'text', value: '저장' }, { type: 'close', id: 'bold-1', kind: 'bold' },
    ]],
    ['deletes a span ID', [
      { type: 'open', id: 'bold-1', kind: 'bold' }, { type: 'text', value: '저장' },
      { type: 'close', id: 'bold-1', kind: 'bold' },
    ]],
    ['changes the nesting relationship', [
      { type: 'open', id: 'bold-1', kind: 'bold' }, { type: 'open', id: 'italic-1', kind: 'italic' },
      { type: 'text', value: '설명서와 저장' }, { type: 'close', id: 'italic-1', kind: 'italic' },
      { type: 'close', id: 'bold-1', kind: 'bold' },
    ]],
  ])('isolates a target that %s', (_label, targetTokens) => {
    const tagged = segment({ sourceText: 'Save Manual', taggedSource: { tagStatus: 'valid', sourceTokens: [
      { type: 'open', id: 'bold-1', kind: 'bold' }, { type: 'text', value: 'Save' },
      { type: 'close', id: 'bold-1', kind: 'bold' }, { type: 'text', value: ' ' },
      { type: 'open', id: 'italic-1', kind: 'italic' }, { type: 'text', value: 'Manual' },
      { type: 'close', id: 'italic-1', kind: 'italic' },
    ] } });
    const analysis = analyzeXliffImport([unit({
      sourceText: tagged.sourceText, sourceTokens: tagged.taggedSource!.sourceTokens, targetTokens,
    })], [tagged]);
    expect(analysis.skippedInlineCodeIssue[0].inlineCodeIssue).toBe('INLINE_CODE_MISMATCH');
  });

  it('isolates inline-code mismatches while processing other valid units', () => {
    const tagged = segment({ segmentId: 'tagged', sourceText: 'Bold', taggedSource: { tagStatus: 'valid', sourceTokens: [
      { type: 'open', id: 'b1', kind: 'bold' }, { type: 'text', value: 'Bold' }, { type: 'close', id: 'b1', kind: 'bold' },
    ] } });
    const plain = segment({ segmentId: 'plain', sourceText: 'Plain' });
    const analysis = analyzeXliffImport([
      unit({ id: 'tagged', sourceText: 'Bold', targetText: '번역', sourceTokens: tagged.taggedSource!.sourceTokens, targetTokens: [
        { type: 'open', id: 'b1', kind: 'italic' }, { type: 'text', value: '번역' }, { type: 'close', id: 'b1', kind: 'italic' },
      ] }),
      unit({ id: 'plain', sourceText: 'Plain', targetText: 'OK' }),
    ], [tagged, plain]);
    expect(analysis.skippedInlineCodeIssue).toHaveLength(1);
    expect(analysis.skippedInlineCodeIssue[0].inlineCodeIssue).toBe('INLINE_CODE_MISMATCH');
    expect(analysis.autoApply.map((item) => item.segment.segmentId)).toEqual(['plain']);
  });

  it('isolates a target with a deleted inline opening code', () => {
    const tagged = segment({ taggedSource: { tagStatus: 'valid', sourceTokens: [
      { type: 'open', id: 'b1', kind: 'bold' }, { type: 'text', value: 'Source text' }, { type: 'close', id: 'b1', kind: 'bold' },
    ] } });
    const analysis = analyzeXliffImport([unit({ sourceTokens: tagged.taggedSource!.sourceTokens, targetTokens: [
      { type: 'text', value: '번역' }, { type: 'close', id: 'b1', kind: 'bold' },
    ] })], [tagged]);
    expect(analysis.skippedInlineCodeIssue[0].inlineCodeIssue).toBe('INLINE_CODE_MISMATCH');
  });

  it('isolates unexpected inline codes for plain-text segments', () => {
    const plain = segment({ sourceText: 'Plain' });
    const analysis = analyzeXliffImport([unit({ sourceText: 'Plain', targetTokens: [
      { type: 'open', id: 'b1', kind: 'bold' }, { type: 'text', value: 'Incoming target' }, { type: 'close', id: 'b1', kind: 'bold' },
    ] })], [plain]);
    expect(analysis.skippedInlineCodeIssue).toHaveLength(1);
    expect(analysis.skippedInlineCodeIssue[0].inlineCodeIssue).toBe('UNEXPECTED_INLINE_CODE');
    expect(analysis.autoApply).toHaveLength(0);
  });

  it('isolates duplicate inline-code IDs as an inline-code mismatch', () => {
    const tagged = segment({ taggedSource: { tagStatus: 'valid', sourceTokens: [
      { type: 'open', id: 'b1', kind: 'bold' }, { type: 'text', value: 'Source text' }, { type: 'close', id: 'b1', kind: 'bold' },
    ] } });
    const analysis = analyzeXliffImport([unit({ sourceTokens: tagged.taggedSource!.sourceTokens, targetTokens: [
      { type: 'open', id: 'b1', kind: 'bold' }, { type: 'text', value: 'One' }, { type: 'close', id: 'b1', kind: 'bold' },
      { type: 'open', id: 'b1', kind: 'bold' }, { type: 'text', value: 'Two' }, { type: 'close', id: 'b1', kind: 'bold' },
    ] })], [tagged]);
    expect(analysis.skippedInlineCodeIssue[0].inlineCodeIssue).toBe('INLINE_CODE_MISMATCH');
  });
});

describe('applyXliffImport', () => {
  it('applies automatic and selected incoming values while retaining skipped and kept segments by reference', () => {
    const automatic = segment({ segmentId: 'automatic', targetDraft: 'Old' });
    const useIncoming = segment({ segmentId: 'use', targetDraft: 'Current', isUserEdited: true });
    const keepCurrent = segment({ segmentId: 'keep', targetDraft: 'Keep', isUserEdited: true });
    const unrelated = segment({ segmentId: 'unrelated', targetDraft: 'Untouched' });
    const result = applyXliffImport(
      [automatic, useIncoming, keepCurrent, unrelated],
      [{ segment: automatic, incoming: unit({ id: 'automatic', targetText: '' }) }],
      [
        { segmentId: 'use', resolution: 'use-incoming', incoming: unit({ id: 'use', targetText: 'Imported' }) } as any,
        { segmentId: 'keep', resolution: 'keep-current', incoming: unit({ id: 'keep', targetText: 'Ignored' }) } as any,
      ], 99,
    );
    expect(result[0]).toMatchObject({ targetDraft: '', status: 'untranslated', origin: 'external-cat', isUserEdited: false, updatedAt: 99 });
    expect(result[1]).toMatchObject({ targetDraft: 'Imported', status: 'draft', origin: 'external-cat', isUserEdited: false, updatedAt: 99 });
    expect(result[2]).toBe(keepCurrent);
    expect(result[3]).toBe(unrelated);
  });
});
