//! Tauri Command Handlers for SmartLinter
//!
//! Provides frontend IPC commands:
//! - `set_always_on_top`: Window pin mode toggling
//! - `analyze_paragraph`: Paragraph QA lint analysis via MicroScopingQueue and QaParser
//! - `execute_ai_command`: Natural language AI revision via MicroScopingQueue

use serde::{Deserialize, Serialize};
use crate::ai::{
    GenerateOptions, MicroScopingQueue, PromptBuilder, QaParser, QaReport, QueueJobRequest,
};
use crate::protocol::ParagraphPayload;
use crate::server::HealthResponse;
use tauri::{State, WebviewWindow};
use tracing::debug;

use crate::indesign_com;

const BRIDGE_HEALTH_URL: &str = "http://127.0.0.1:49152/health";

/// Bridge connection status returned to the dashboard.
/// Matches the TypeScript `BridgeStatusPayload` interface.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeStatusDto {
    pub connected: bool,
    pub editor_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_document: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl From<HealthResponse> for BridgeStatusDto {
    fn from(health: HealthResponse) -> Self {
        Self {
            connected: health.connected,
            editor_type: health.active_editor,
            session_id: health.session_id,
            active_document: None,
            version: Some(health.version),
        }
    }
}

/// Fetches the current Local Bridge health state for the dashboard.
#[tauri::command]
pub async fn get_bridge_status() -> Result<BridgeStatusDto, String> {
    let health = reqwest::get(BRIDGE_HEALTH_URL)
        .await
        .map_err(|e| format!("Failed to request bridge health: {}", e))?
        .error_for_status()
        .map_err(|e| format!("Bridge health request failed: {}", e))?
        .json::<HealthResponse>()
        .await
        .map_err(|e| format!("Failed to decode bridge health response: {}", e))?;

    Ok(health.into())
}

/// Returns whether a running InDesign instance is registered for COM automation.
#[tauri::command]
pub fn check_indesign_status() -> Result<bool, String> {
    indesign_com::detect_running_indesign()
}

/// Attaches to the running InDesign instance and starts the persistent bridge daemon.
#[tauri::command]
pub fn connect_indesign() -> Result<(), String> {
    let daemon_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("plugins")
        .join("indesign")
        .join("extendscript")
        .join("smartlinter_daemon.jsx");

    indesign_com::inject_daemon_script(&daemon_path)
}

/// Result DTO for AI interactive natural language revision command.
/// Matches TypeScript `AiCommandResult` interface.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AiCommandResultDto {
    /// Revised text proposal generated by LLM.
    pub suggested_text: String,
    /// Total inference and processing latency in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<u64>,
    /// Model name used for execution.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// Optional error message if generation failed or degraded.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// Sets the always-on-top (Pin Mode) state for the application window.
#[tauri::command]
pub async fn set_always_on_top(window: WebviewWindow, pinned: bool) -> Result<bool, String> {
    window
        .set_always_on_top(pinned)
        .map_err(|e| format!("Failed to set always on top: {}", e))?;
    Ok(pinned)
}

/// Analyzes paragraph text for translation/style QA violations using local LLM and MicroScopingQueue.
#[tauri::command]
pub async fn analyze_paragraph(
    paragraph: ParagraphPayload,
    queue: State<'_, MicroScopingQueue>,
) -> Result<QaReport, String> {
    debug!(
        "Received analyze_paragraph command for paragraph '{}' (len: {})",
        paragraph.paragraph_id,
        paragraph.text.len()
    );

    let builder = PromptBuilder::new()
        .source(&paragraph.source)
        .target(&paragraph.text);

    let req = builder.build_queue_request(&paragraph.paragraph_id);

    let job_result = queue
        .submit(req)
        .await
        .map_err(|e| format!("LLM QA inference error: {}", e))?;

    debug!(
        "QA analysis for '{}' completed in {}ms using '{}'",
        paragraph.paragraph_id, job_result.duration_ms, job_result.model_used
    );

    let report = QaParser::parse(&job_result.response);
    Ok(report)
}

/// Executes an interactive natural language AI revision command on a target paragraph.
#[tauri::command]
pub async fn execute_ai_command(
    instruction: String,
    paragraph: ParagraphPayload,
    queue: State<'_, MicroScopingQueue>,
) -> Result<AiCommandResultDto, String> {
    debug!(
        "Received execute_ai_command '{}' for paragraph '{}'",
        instruction, paragraph.paragraph_id
    );

    let system_instruction = "You are a professional Korean writing assistant and editor. Revise the given paragraph strictly according to the user's instruction. Output ONLY the revised text with no explanations, conversational preamble, or markdown formatting.";

    let user_prompt = format!(
        "Instruction: {}\n\nParagraph to revise:\n{}",
        instruction.trim(),
        paragraph.text.trim()
    );

    let options = GenerateOptions {
        temperature: Some(0.3),
        top_p: Some(0.9),
        num_ctx: Some(2048),
        ..Default::default()
    };

    let req = QueueJobRequest::new(&paragraph.paragraph_id, user_prompt)
        .with_system(system_instruction)
        .with_options(options);

    let job_result = queue
        .submit(req)
        .await
        .map_err(|e| format!("AI command execution error: {}", e))?;

    let suggested_text = clean_ai_suggested_text(&job_result.response, &paragraph.text);

    Ok(AiCommandResultDto {
        suggested_text,
        duration_ms: Some(job_result.duration_ms),
        model: Some(job_result.model_used),
        error: None,
    })
}

/// Extracts and sanitizes the proposed replacement text from raw LLM output.
pub fn clean_ai_suggested_text(raw: &str, original_fallback: &str) -> String {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return original_fallback.to_string();
    }

    // 1. If wrapped in markdown code fence, extract content inside
    let unescaped = if let Some(extracted) = extract_fence_content(trimmed) {
        extracted
    } else {
        trimmed.to_string()
    };

    // 2. Strip common conversational headers / prefixes (e.g. "수정된 문단:", "제안:")
    let without_prefix = strip_conversational_prefixes(&unescaped);

    // 3. Strip outer enclosing quotes if present (e.g. `"..."` or `“...”` or `「...」`)
    let cleaned = strip_surrounding_quotes(&without_prefix);

    if cleaned.is_empty() {
        original_fallback.to_string()
    } else {
        cleaned
    }
}

fn extract_fence_content(text: &str) -> Option<String> {
    if let Some(start) = text.find("```") {
        let content_after = &text[start + 3..];
        let content_body = if let Some(nl) = content_after.find('\n') {
            &content_after[nl + 1..]
        } else {
            content_after
        };

        if let Some(end) = content_body.rfind("```") {
            let inner = content_body[..end].trim();
            if !inner.is_empty() {
                return Some(inner.to_string());
            }
        } else {
            let inner = content_body.trim();
            if !inner.is_empty() {
                return Some(inner.to_string());
            }
        }
    }
    None
}

fn strip_conversational_prefixes(text: &str) -> String {
    let trimmed = text.trim();
    let lower = trimmed.to_lowercase();
    let prefixes = [
        "수정된 문단:",
        "수정된 문장:",
        "수정안:",
        "수정 텍스트:",
        "수정된 텍스트:",
        "제안:",
        "제안된 문장:",
        "here is the revised paragraph:",
        "here is the revised text:",
        "revised paragraph:",
        "revised text:",
    ];

    for prefix in prefixes {
        if lower.starts_with(prefix) {
            let remaining = trimmed[prefix.len()..].trim();
            if !remaining.is_empty() {
                return remaining.to_string();
            }
        }
    }

    trimmed.to_string()
}

fn strip_surrounding_quotes(text: &str) -> String {
    let t = text.trim();
    let quote_pairs = [
        ("\"", "\""),
        ("'", "'"),
        ("“", "”"),
        ("「", "」"),
        ("『", "』"),
    ];

    for (start_q, end_q) in quote_pairs {
        if t.starts_with(start_q) && t.ends_with(end_q) && t.len() >= start_q.len() + end_q.len() {
            let inner = &t[start_q.len()..t.len() - end_q.len()];
            return inner.trim().to_string();
        }
    }

    t.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ai::LocalLlmProvider;

    #[test]
    fn test_get_bridge_status_maps_health_response_to_dashboard_payload() {
        let status = BridgeStatusDto::from(HealthResponse {
            status: "healthy".to_string(),
            service: "SmartLinter Local Bridge".to_string(),
            version: "0.1.0".to_string(),
            connected: true,
            active_editor: Some("Word".to_string()),
            session_id: Some("session-123".to_string()),
        });

        assert_eq!(status.connected, true);
        assert_eq!(status.editor_type.as_deref(), Some("Word"));
        assert_eq!(status.session_id.as_deref(), Some("session-123"));
        assert_eq!(status.active_document, None);
        assert_eq!(status.version.as_deref(), Some("0.1.0"));
    }

    #[test]
    fn test_clean_ai_suggested_text_plain() {
        let raw = "데이터베이스 스냅샷은 24시간마다 자동 생성됩니다.";
        let cleaned = clean_ai_suggested_text(raw, "원문");
        assert_eq!(cleaned, "데이터베이스 스냅샷은 24시간마다 자동 생성됩니다.");
    }

    #[test]
    fn test_clean_ai_suggested_text_with_fences() {
        let raw = "```text\n데이터베이스 스냅샷은 24시간마다 자동 생성됩니다.\n```";
        let cleaned = clean_ai_suggested_text(raw, "원문");
        assert_eq!(cleaned, "데이터베이스 스냅샷은 24시간마다 자동 생성됩니다.");
    }

    #[test]
    fn test_clean_ai_suggested_text_with_quotes() {
        let raw = "\"데이터베이스 스냅샷은 24시간마다 자동 생성됩니다.\"";
        let cleaned = clean_ai_suggested_text(raw, "원문");
        assert_eq!(cleaned, "데이터베이스 스냅샷은 24시간마다 자동 생성됩니다.");

        let raw_curly = "“데이터베이스 스냅샷은 24시간마다 자동 생성됩니다.”";
        let cleaned_curly = clean_ai_suggested_text(raw_curly, "원문");
        assert_eq!(cleaned_curly, "데이터베이스 스냅샷은 24시간마다 자동 생성됩니다.");
    }

    #[test]
    fn test_clean_ai_suggested_text_with_prefix() {
        let raw = "수정안: 데이터베이스 스냅샷은 24시간마다 자동 생성됩니다.";
        let cleaned = clean_ai_suggested_text(raw, "원문");
        assert_eq!(cleaned, "데이터베이스 스냅샷은 24시간마다 자동 생성됩니다.");
    }

    #[test]
    fn test_clean_ai_suggested_text_empty_fallback() {
        let raw = "   ";
        let cleaned = clean_ai_suggested_text(raw, "원문 텍스트");
        assert_eq!(cleaned, "원문 텍스트");
    }

    #[test]
    fn test_ai_command_result_dto_serialization() {
        let dto = AiCommandResultDto {
            suggested_text: "수정된 텍스트".to_string(),
            duration_ms: Some(150),
            model: Some("qwen2.5:7b".to_string()),
            error: None,
        };

        let json_str = serde_json::to_string(&dto).unwrap();
        assert!(json_str.contains(r#""suggestedText":"수정된 텍스트""#));
        assert!(json_str.contains(r#""durationMs":150"#));
        assert!(json_str.contains(r#""model":"qwen2.5:7b""#));
        assert!(!json_str.contains(r#""error""#));
    }

    #[tokio::test]
    async fn test_analyze_paragraph_pipeline_with_mock() {
        use std::sync::Arc;
        let mock = Arc::new(crate::ai::MockLlmProvider::new());
        mock.set_fixed_response(r#"{
            "status": "FAIL",
            "issues": [
                {
                    "category": "번역투",
                    "originalSegment": "업데이트되어지게 됩니다",
                    "suggestedSegment": "업데이트됩니다",
                    "reason": "이중 피동 표현 지양",
                    "severity": "HIGH"
                }
            ]
        }"#).await;

        let queue = MicroScopingQueue::new(mock.clone(), "qwen2.5:7b");

        let para = ParagraphPayload {
            paragraph_id: "test-para-1".to_string(),
            text: "데이터가 업데이트되어지게 됩니다.".to_string(),
            hash: "dummyhash".to_string(),
            source: "Document.docx".to_string(),
            target: None,
            timestamp: 1000,
            editor_type: crate::protocol::EditorType::Word,
        };

        let builder = PromptBuilder::new().source(&para.source).target(&para.text);
        let req = builder.build_queue_request(&para.paragraph_id);
        let job_res = queue.submit(req).await.unwrap();
        let report = QaParser::parse(&job_res.response);

        assert_eq!(report.status, crate::ai::QaStatus::Fail);
        assert_eq!(report.issues.len(), 1);
        assert_eq!(report.issues[0].category, "번역투");
        assert_eq!(report.issues[0].suggested_segment, "업데이트됩니다");
    }

    #[tokio::test]
    async fn test_execute_ai_command_pipeline_with_mock() {
        use std::sync::Arc;
        let mock = Arc::new(crate::ai::MockLlmProvider::new());
        mock.set_fixed_response("데이터가 즉시 업데이트됩니다.").await;

        let queue = MicroScopingQueue::new(mock.clone(), "qwen2.5:7b");

        let para = ParagraphPayload {
            paragraph_id: "test-para-2".to_string(),
            text: "데이터가 업데이트되어지게 됩니다.".to_string(),
            hash: "dummyhash".to_string(),
            source: "Document.docx".to_string(),
            target: None,
            timestamp: 1000,
            editor_type: crate::protocol::EditorType::Word,
        };

        let req = QueueJobRequest::new(&para.paragraph_id, "더 간결하게 다듬어줘");
        let job_res = queue.submit(req).await.unwrap();
        let suggested_text = clean_ai_suggested_text(&job_res.response, &para.text);

        assert_eq!(suggested_text, "데이터가 즉시 업데이트됩니다.");
    }

    #[tokio::test]
    async fn test_live_ollama_analyze_paragraph_and_execute_ai_command() {
        use std::sync::Arc;
        let provider = Arc::new(crate::ai::OllamaProvider::with_default_url().with_timeout(std::time::Duration::from_secs(90)));
        let health = provider.health_check().await.unwrap();
        if !health.is_alive {
            println!("Skipping live test: Ollama offline");
            return;
        }

        let models = provider.list_models().await.unwrap_or_default();
        if models.is_empty() {
            println!("Skipping live test: No Ollama models installed");
            return;
        }

        let model_to_use = models
            .iter()
            .find(|m| m.name.starts_with("qwen2.5:7b") || m.name.starts_with("qwen2.5"))
            .map(|m| m.name.clone())
            .unwrap_or_else(|| models[0].name.clone());

        let queue = MicroScopingQueue::with_config(
            provider.clone(),
            crate::ai::QueueConfig::new(&model_to_use).with_timeout(std::time::Duration::from_secs(90)),
        );

        // 1. Test live analyze_paragraph flow with qwen2.5:7b
        let para = ParagraphPayload {
            paragraph_id: "live-para-qa".to_string(),
            text: "데이터베이스 스냅샷은 24시간마다 자동적으로 생성되어지는 구조이며 백업되어지게 됩니다.".to_string(),
            hash: "livehash".to_string(),
            source: "The database snapshot is automatically created every 24 hours and backed up.".to_string(),
            target: None,
            timestamp: 1000,
            editor_type: crate::protocol::EditorType::Word,
        };

        let builder = PromptBuilder::new().source(&para.source).target(&para.text);
        let req = builder.build_queue_request(&para.paragraph_id);
        let job_res = queue.submit(req).await.expect("Live QA job failed");
        let report = QaParser::parse(&job_res.response);

        println!("[Live QA Report Status]: {}", report.status);
        println!("[Live QA Issues Count]: {}", report.issues.len());
        for issue in &report.issues {
            println!("  - Issue: [{}] '{}' -> '{}' ({})", issue.category, issue.original_segment, issue.suggested_segment, issue.reason);
        }
        assert!(report.raw_response.is_some() || !report.issues.is_empty() || report.status == crate::ai::QaStatus::Pass);

        // 2. Test live execute_ai_command flow with qwen2.5:7b
        let cmd_prompt = format!(
            "Instruction: 더 간결하고 능동적인 문장으로 수정해줘\n\nParagraph to revise:\n{}",
            para.text
        );
        let cmd_req = QueueJobRequest::new(&para.paragraph_id, cmd_prompt)
            .with_system("You are a professional Korean writing assistant and editor. Revise the given paragraph strictly according to the user's instruction. Output ONLY the revised text with no explanations, conversational preamble, or markdown formatting.");

        let cmd_res = queue.submit(cmd_req).await.expect("Live AI command failed");
        let cleaned_suggestion = clean_ai_suggested_text(&cmd_res.response, &para.text);

        println!("[Live AI Command Result]: '{}' (in {}ms, model: {})", cleaned_suggestion, cmd_res.duration_ms, cmd_res.model_used);
        assert!(!cleaned_suggestion.trim().is_empty());
        assert_ne!(cleaned_suggestion, "");
    }
}
